In [286]:
import pandas as pd
df = pd.read_csv('dataset.csv')
df.set_index('Title', inplace=True)
df.dropna(how='all', inplace=True)

In [287]:
category = pd.read_csv('category.csv')
category.set_index('Title', inplace=True)
category.astype(int)

,action,spooks,real_monsters,hurt_children,hurt_animals,blood,badass,romance,funny,artism,parody,body,horror,inversion,atmospheric,paranormal,monsters,zombie
Title,,,,,,,,,,,,,,,,,,
willy wonderland,1,0,0,0,0,1,1,0,1,0,1,0,0,1,0,0,1,0
tigers are not afraid,0,1,1,1,0,0,0,0,0,1,0,0,1,0,1,1,0,0
satanic panic,1,0,1,0,1,1,1,0,1,0,1,0,0,1,0,0,1,0
little monsters,1,0,1,1,0,1,0,1,1,0,1,0,0,0,0,0,0,1
underwater,1,1,0,0,0,0,1,1,0,0,0,0,1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Blair witch (2016),0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0
vvitch,1,1,1,1,1,1,0,1,0,0,0,0,0,0,1,1,0,0
Poltergeist,1,1,0,1,0,0,1,1,0,0,0,0,0,0,0,1,0,0
Scare me,0,1,0,0,0,0,0,1,1,1,1,0,0,1,1,0,0,0
Caveat,0,1,1,1,0,0,0,0,0,1,0,0,0,0,1,1,0,0

In [288]:
for person in df:
    new_x=[]
    for x in df[person]:
        if isinstance(x, str):
            if ',' in x:
                x='.'.join(x.split(","))
        new_x.append(x)
    df[person]=new_x
df=df.astype(float)
df

,xero,osar,marta,stawska,karolina,ania5,kacper,sasiadka6,2kej,wiku,rafal,alicja
Title,,,,,,,,,,,,
willy wonderland,8.0,8.0,8.5,10.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN
tigers are not afraid,1.0,1.0,2.0,2.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
satanic panic,7.0,3.0,3.0,5.0,2.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN
little monsters,3.0,5.0,4.0,NaN,NaN,7.0,3.0,5.0,NaN,NaN,NaN,NaN
underwater,9.0,8.5,8.0,NaN,NaN,9.5,9.0,7.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
Blair witch (2016),5.0,8.0,NaN,7.0,NaN,NaN,4.0,3.0,NaN,NaN,8.0,NaN
vvitch,9.0,7.0,NaN,4.0,NaN,NaN,4.0,5.5,NaN,NaN,9.0,NaN
Poltergeist,3.0,5.0,4.0,NaN,NaN,5.0,7.5,NaN,NaN,NaN,4.5,NaN
Scare me,10.0,10.0,9.0,NaN,NaN,5.0,7.0,NaN,NaN,NaN,9.5,NaN
Caveat,9.0,6.0,NaN,NaN,NaN,NaN,5.5,NaN,NaN,NaN,6.0,NaN

In [289]:
df.mean()

xero         6.229167
osar         5.640625
marta        5.263636
stawska      5.409091
karolina     4.075000
ania5        6.105263
kacper       4.880597
sasiadka6    5.230769
2kej         5.812500
wiku         6.714286
rafal        5.351852
alicja       5.906250
dtype: float64

In [290]:
df.count()

xero         72
osar         64
marta        55
stawska      44
karolina     20
ania5        19
kacper       67
sasiadka6    52
2kej         24
wiku         21
rafal        27
alicja       16
dtype: int64

In [291]:
import numpy as np
import matplotlib
import matplotlib.pyplot as pl
import numpy as np
import csv
import pandas as pd
from sklearn import linear_model, metrics
from sklearn.model_selection import train_test_split

# KOGO SPRAWDZAMY

In [340]:
who='kacper'

In [341]:
df

,xero,osar,marta,stawska,karolina,ania5,kacper,sasiadka6,2kej,wiku,rafal,alicja
Title,,,,,,,,,,,,
willy wonderland,8.0,8.0,8.5,10.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN
tigers are not afraid,1.0,1.0,2.0,2.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
satanic panic,7.0,3.0,3.0,5.0,2.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN
little monsters,3.0,5.0,4.0,NaN,NaN,7.0,3.0,5.0,NaN,NaN,NaN,NaN
underwater,9.0,8.5,8.0,NaN,NaN,9.5,9.0,7.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
Blair witch (2016),5.0,8.0,NaN,7.0,NaN,NaN,4.0,3.0,NaN,NaN,8.0,NaN
vvitch,9.0,7.0,NaN,4.0,NaN,NaN,4.0,5.5,NaN,NaN,9.0,NaN
Poltergeist,3.0,5.0,4.0,NaN,NaN,5.0,7.5,NaN,NaN,NaN,4.5,NaN
Scare me,10.0,10.0,9.0,NaN,NaN,5.0,7.0,NaN,NaN,NaN,9.5,NaN
Caveat,9.0,6.0,NaN,NaN,NaN,NaN,5.5,NaN,NaN,NaN,6.0,NaN

In [342]:
data=df[who]
data.dropna(inplace=True)

In [343]:
category=category.iloc[data]
category

,action,spooks,real_monsters,hurt_children,hurt_animals,blood,badass,romance,funny,artism,parody,body,horror,inversion,atmospheric,paranormal,monsters,zombie
Title,,,,,,,,,,,,,,,,,,
psycho goreman,1,0,1,1,0,1,1,0,1,1,1,1,0,1,0,0,1,0
satanic panic,1,0,1,0,1,1,1,0,1,0,1,0,0,1,0,0,1,0
little monsters,1,0,1,1,0,1,0,1,1,0,1,0,0,0,0,0,0,1
underwater,1,1,0,0,0,0,1,1,0,0,0,0,1,0,1,0,1,0
satanic panic,1,0,1,0,1,1,1,0,1,0,1,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
little monsters,1,0,1,1,0,1,0,1,1,0,1,0,0,0,0,0,0,1
little monsters,1,0,1,1,0,1,0,1,1,0,1,0,0,0,0,0,0,1
psycho goreman,1,0,1,1,0,1,1,0,1,1,1,1,0,1,0,0,1,0
psycho goreman,1,0,1,1,0,1,1,0,1,1,1,1,0,1,0,0,1,0
little monsters,1,0,1,1,0,1,0,1,1,0,1,0,0,0,0,0,0,1

In [344]:
X_train, X_test, y_train, y_test = train_test_split(category, data, test_size=0.2, random_state=2)

In [345]:
print("train:",len(X_train),"test:",len(X_test))

train: 53 test: 14

In [346]:
regr = linear_model.LinearRegression()
regr.fit(X_train, y_train)
predictions = regr.predict(X_test)

In [347]:
predictions

array([5.8       , 7.125     , 4.39285714, 4.52941176, 4.52941176,
       7.125     , 4.39285714, 7.125     , 7.125     , 5.8       ,
       4.11111111, 4.11111111, 5.8       , 7.125     ])

In [348]:
y_test

Title
the lamb                 1.5
choose or die            7.0
get out                  6.5
antlers                  4.0
us                       4.0
cube 3                   7.0
the wretched             6.0
willy wonderland         7.0
The Whole Truth          7.0
birdemic 2               1.0
robert 5                 3.0
47 meters                3.0
tigers are not afraid    1.0
Poltergeist              7.5
Name: kacper, dtype: float64

In [349]:
for i in range(len(y_test)):
    print(y_test.keys()[i],"predykcja: ", predictions[i], "prawda:", y_test[i])

the lamb predykcja:  5.799999999999999 prawda: 1.5
choose or die predykcja:  7.124999999999999 prawda: 7.0
get out predykcja:  4.392857142857143 prawda: 6.5
antlers predykcja:  4.529411764705881 prawda: 4.0
us predykcja:  4.529411764705881 prawda: 4.0
cube 3 predykcja:  7.124999999999999 prawda: 7.0
the wretched predykcja:  4.392857142857143 prawda: 6.0
willy wonderland predykcja:  7.124999999999999 prawda: 7.0
The Whole Truth predykcja:  7.124999999999999 prawda: 7.0
birdemic 2 predykcja:  5.799999999999999 prawda: 1.0
robert 5 predykcja:  4.111111111111111 prawda: 3.0
47 meters predykcja:  4.111111111111111 prawda: 3.0
tigers are not afraid predykcja:  5.799999999999999 prawda: 1.0
Poltergeist predykcja:  7.124999999999999 prawda: 7.5

In [350]:
for i in range(len(category.columns)):
    print(category.columns[i], regr.coef_[i])

action 0.0
spooks -0.1800880604246277
real_monsters 0.09849235226736754
hurt_children 0.2255011053676909
hurt_animals -0.12700875310032397
blood 0.09849235226736748
badass 0.3015418194769316
romance -0.3184384635870388
funny 0.18008806042462785
artism 0.4454472166873623
parody 0.18008806042462785
body 0.5270429248446228
horror -0.18008806042462785
inversion 0.40003417174429917
atmospheric -0.18008806042462785
paranormal 0.0
monsters 0.3015418194769317
zombie -0.3015418194769317